language: cpp

compiler:
        - clang
        - gcc

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y openssl-devel protobuf-devel boost-devel
 
script: ./scripts/travis_build.sh
