language: cpp

compiler:
        - clang
        - gcc

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install

install:
        - sudo apt-get install -y libssl-dev protobuf-compiler libprotobuf-dev libboost-date-time-dev
        - ls -alR /usr/include/boost
 
script: ./scripts/travis_build.sh
