language: cpp

compiler:
        - clang
        - gcc

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -y openssl_devel protobuf_devel boost_devel
 
script: ./scripts/travis_build.sh
